### ISSUE TITLE
Misleading benchmarks

### ISSUE THREAD

**Issue by richardpl** [pdeljanov/Symphonia#179] opened 2023-01-26 21:22 UTC
ffmpeg utility tool is certainly not designed nor correct way to benchmark only demuxing and decoding path of audio files processing.

One should use instead modified demuxing_decoding from doc/examples so it does not write any data and thus comparison is fair.

The most questionable benchmark result is PCM in WAV, which is basically only memcpy calls.

When doing independent benchmarks, results for PCM in WAV are 1.5 and around 2.0 slower Symphonia decoding then libavcodec+libavformat via demuxing_decoding demo in examples.

**Comment by pdeljanov** [comment] 2023-01-27 00:06
I don't think`ffmpeg` will be writing anything since the null muxer is a no-op. According to the ffmpeg [Trac](https://trac.ffmpeg.org/wiki/Null) this is a valid way to test decoding speed.

That being said, I can appreciate that the `ffmpeg` utility may have more overhead than a simple tight decoding loop. I modified the example you referenced (gist is [here](https://gist.github.com/pdeljanov/db7fd9af6e3ef598d27680c93fa04c7a)) and re-tested on my system (i7-4790k).

The results I get are below. PCM is basically equal now. Interestingly, the more computationally complex codecs are faster with `libavcodec/libavformat` now, which is unexpected if we are assuming the overhead is coming from the `ffmpeg` utility. My assumption would be the decode time would be much greater than any overhead from `ffmpeg`.

---

```
Benchmark 1: ./ffbench '/tmp/symphonia/bench/aac_44khz_1.m4a'
  Time (mean ± σ):     144.8 ms ±   9.4 ms    [User: 134.8 ms, System: 8.7 ms]
  Range (min … max):   139.5 ms … 182.6 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/aac_44khz_1.m4a'
  Time (mean ± σ):     227.2 ms ±   6.5 ms    [User: 219.4 ms, System: 3.7 ms]
  Range (min … max):   221.2 ms … 245.1 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/aac_44khz_2.m4a'
  Time (mean ± σ):     128.7 ms ±   3.6 ms    [User: 119.3 ms, System: 8.4 ms]
  Range (min … max):   125.1 ms … 137.1 ms    21 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/aac_44khz_2.m4a'
  Time (mean ± σ):     197.3 ms ±   2.5 ms    [User: 190.7 ms, System: 2.8 ms]
  Range (min … max):   194.9 ms … 203.3 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/adpcm_ima_44khz.wav'
  Time (mean ± σ):     113.3 ms ±   2.5 ms    [User: 104.9 ms, System: 7.6 ms]
  Range (min … max):   110.9 ms … 121.9 ms    26 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/adpcm_ima_44khz.wav'
  Time (mean ± σ):      79.8 ms ±   1.9 ms    [User: 75.4 ms, System: 3.8 ms]
  Range (min … max):    77.7 ms …  86.9 ms    36 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/adpcm_ms_44khz.wav'
  Time (mean ± σ):     103.1 ms ±   2.7 ms    [User: 93.9 ms, System: 8.3 ms]
  Range (min … max):   100.7 ms … 111.1 ms    28 runs
  
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/adpcm_ms_44khz.wav'
  Time (mean ± σ):      97.2 ms ±   2.7 ms    [User: 93.1 ms, System: 3.2 ms]
  Range (min … max):    94.3 ms … 104.4 ms    30 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/alac_16bit_44khz.m4a'
  Time (mean ± σ):     600.6 ms ±   4.4 ms    [User: 587.3 ms, System: 8.9 ms]
  Range (min … max):   592.9 ms … 607.8 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/alac_16bit_44khz.m4a'
  Time (mean ± σ):     529.2 ms ±   5.4 ms    [User: 518.2 ms, System: 4.9 ms]
  Range (min … max):   522.0 ms … 538.5 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/alac_32bit_96khz.m4a'
  Time (mean ± σ):      1.732 s ±  0.008 s    [User: 1.692 s, System: 0.030 s]
  Range (min … max):    1.719 s …  1.750 s    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/alac_32bit_96khz.m4a'
  Time (mean ± σ):      1.650 s ±  0.011 s    [User: 1.614 s, System: 0.024 s]
  Range (min … max):    1.636 s …  1.689 s    20 runs

---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/flac_16bit_44khz.flac'
  Time (mean ± σ):     258.9 ms ±   3.9 ms    [User: 244.4 ms, System: 12.3 ms]
  Range (min … max):   255.4 ms … 267.9 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/flac_16bit_44khz.flac'
  Time (mean ± σ):     222.4 ms ±   3.1 ms    [User: 212.9 ms, System: 7.6 ms]
  Range (min … max):   219.4 ms … 229.8 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/flac_24bit_48khz.flac'
  Time (mean ± σ):     270.9 ms ±   4.1 ms    [User: 253.1 ms, System: 15.5 ms]
  Range (min … max):   266.9 ms … 278.4 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/flac_24bit_48khz.flac'
  Time (mean ± σ):     247.9 ms ±   4.3 ms    [User: 235.1 ms, System: 10.6 ms]
  Range (min … max):   243.2 ms … 257.3 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/flac_24bit_96khz.flac'
  Time (mean ± σ):     232.0 ms ±   6.5 ms    [User: 218.7 ms, System: 11.5 ms]
  Range (min … max):   227.3 ms … 255.1 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/flac_24bit_96khz.flac'
  Time (mean ± σ):     206.6 ms ±   3.1 ms    [User: 197.2 ms, System: 7.7 ms]
  Range (min … max):   203.2 ms … 213.3 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/mp1_44khz_192kbps.mp1'
  Time (mean ± σ):     213.7 ms ±   4.3 ms    [User: 203.7 ms, System: 8.2 ms]
  Range (min … max):   208.6 ms … 223.2 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/mp1_44khz_192kbps.mp1'
  Time (mean ± σ):     105.6 ms ±   2.8 ms    [User: 102.2 ms, System: 2.5 ms]
  Range (min … max):   103.1 ms … 113.4 ms    28 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/mp1_44khz_448kbps.mp1'
  Time (mean ± σ):     235.7 ms ±   3.7 ms    [User: 224.9 ms, System: 9.1 ms]
  Range (min … max):   229.2 ms … 242.3 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/mp1_44khz_448kbps.mp1'
  Time (mean ± σ):     121.2 ms ±   3.2 ms    [User: 116.9 ms, System: 3.2 ms]
  Range (min … max):   117.9 ms … 129.5 ms    24 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/mp2_44khz_128kbps.mp2'
  Time (mean ± σ):     186.8 ms ±   5.9 ms    [User: 177.1 ms, System: 8.2 ms]
  Range (min … max):   181.6 ms … 199.4 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/mp2_44khz_128kbps.mp2'
  Time (mean ± σ):     118.6 ms ±   2.4 ms    [User: 115.6 ms, System: 2.2 ms]
  Range (min … max):   116.0 ms … 126.5 ms    24 runs

---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/mp2_44khz_384kbps.mp2'
  Time (mean ± σ):     138.8 ms ±   4.2 ms    [User: 130.6 ms, System: 7.0 ms]
  Range (min … max):   136.0 ms … 155.2 ms    21 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/mp2_44khz_384kbps.mp2'
  Time (mean ± σ):      79.1 ms ±   2.4 ms    [User: 76.3 ms, System: 2.3 ms]
  Range (min … max):    76.6 ms …  89.6 ms    36 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/mp3_44khz_128kbps.mp3'
  Time (mean ± σ):     266.7 ms ±   3.3 ms    [User: 256.9 ms, System: 7.5 ms]
  Range (min … max):   261.7 ms … 273.5 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/mp3_44khz_128kbps.mp3'
  Time (mean ± σ):     345.4 ms ±   5.3 ms    [User: 339.6 ms, System: 2.9 ms]
  Range (min … max):   339.5 ms … 358.2 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/mp3_44khz_320kbps.mp3'
  Time (mean ± σ):     237.4 ms ±   3.5 ms    [User: 226.0 ms, System: 9.4 ms]
  Range (min … max):   232.8 ms … 244.3 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/mp3_44khz_320kbps.mp3'
  Time (mean ± σ):     251.2 ms ±   4.3 ms    [User: 245.7 ms, System: 3.4 ms]
  Range (min … max):   247.7 ms … 264.1 ms    20 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/pcm_s32le_44khz.wav'
  Time (mean ± σ):      52.2 ms ±   1.5 ms    [User: 36.9 ms, System: 14.9 ms]
  Range (min … max):    49.2 ms …  58.7 ms    55 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/pcm_s32le_44khz.wav'
  Time (mean ± σ):      43.7 ms ±   1.5 ms    [User: 35.0 ms, System: 8.3 ms]
  Range (min … max):    41.5 ms …  51.9 ms    65 runs
 
---

Benchmark 1: ./ffbench '/tmp/symphonia/bench/vorbis_44khz_256kbps.ogg'
  Time (mean ± σ):     321.0 ms ±   4.2 ms    [User: 308.7 ms, System: 9.9 ms]
  Range (min … max):   316.0 ms … 327.9 ms    20 runs
 
Benchmark 2: ./target/release/symphonia-play --decode-only '/tmp/symphonia/bench/vorbis_44khz_256kbps.ogg'
  Time (mean ± σ):     474.4 ms ±  13.3 ms    [User: 467.4 ms, System: 3.8 ms]
  Range (min … max):   464.2 ms … 518.7 ms    20 runs
```

**Comment by richardpl** [comment] 2023-01-27 18:03
-f null will convert any audio to pcm_s16le but will drop it at end. So it does some non-trivial encoding work.

**Comment by pdeljanov** [comment] 2023-01-29 18:03
> -f null will convert any audio to pcm_s16le but will drop it at end. So it does some non-trivial encoding work.

Thanks. That makes sense. We'll re-run the benchmark with the new tool.

---

Hi @Shnatsel,

It looks like using the `ffmpeg` utility to benchmark adds additional overhead that skews our results (see above discussion). Could you build the utility in the [gist](https://gist.github.com/pdeljanov/db7fd9af6e3ef598d27680c93fa04c7a) using the command below.

```shell
gcc -lavutil -lavcodec -lavformat -O3 ffbench.c -o ffbench
```

Then use this updated hyperfine command to collect results for the `v0.5.2` tag.

```sh
#!/bin/bash
IN="${1}"
hyperfine --export-json "${IN}.json" --warmup 3 -m 20 "ffmpeg -threads 1 -benchmark -v 0 -i ${IN} -f null -" "./ffbench ${IN}" "./target/release/symphonia-play --decode-only ${IN}"
```

I've done some experiments to see how we can close the gap again, and using `rustfft` instead of our own FFT seems to get us most of the way there. So could you also run the benchmarks against the `experimental-opts` branch as well?

**Comment by Shnatsel** [comment] 2023-01-29 19:58
Doesn't compile for me, here's the output: https://gist.github.com/Shnatsel/4043493bcbdacf20134a9918827d24a0

I've installed all the development headers already. Maybe my ffmpeg is too old or something.

**Comment by Shnatsel** [comment] 2023-01-29 20:26
The `experimental-opts` branch does seem to be a big help for AAC-LC and Vorbis. The results comparing 0.5.2 with it are attached.

[experimental-opts-benches.tar.gz](https://github.com/pdeljanov/Symphonia/files/10530761/experimental-opts-benches.tar.gz)

**Comment by pdeljanov** [comment] 2023-01-29 20:45
> Doesn't compile for me, here's the output: https://gist.github.com/Shnatsel/4043493bcbdacf20134a9918827d24a0
> 
> I've installed all the development headers already. Maybe my ffmpeg is too old or something.

Hmmm, on Arch this command worked. It looks like it didn't link any of the libraries. You may need to specify the `-L` with the folder containing the libraries on your system. For example `-L/usr/lib`. I don't have an Ubuntu install handy at the moment to give you an exact path though.

> The `experimental-opts` branch does seem to be a big help for AAC-LC and Vorbis. The results comparing 0.5.2 with it are attached.
> 
> [experimental-opts-benches.tar.gz](https://github.com/pdeljanov/Symphonia/files/10530761/experimental-opts-benches.tar.gz)

Yup, that's expected.

The decoders with the biggest losses are the ones that use the MDCT (implemented in terms of a FFT). MP3 is also one of these codecs, but it uses a custom implementation rather than the the one in `symphonia-core` so you wouldn't see a change.

The rest still benchmark on-par or favourable per my tests so I'll leave them.

**Comment by Shnatsel** [comment] 2023-01-29 20:59
Neither `/usr/include/x86_64-linux-gnu/` where the header files are nor `/usr/lib/x86_64-linux-gnu` where the actual libraries are worked.

@richardpl Is there really no way to benchmark ffmpeg other than a code snippet without any build system support? Not that autotools would be any easier to use, just that I'd expect my distro to already have this package compiled.

**Comment by pdeljanov** [comment] 2023-01-29 21:04
Weird. I'll likely need to try in a VM to get you a working command.

The code snippet is based off a stripped down example from the FFMpeg repo. You could probably just replace the decoding_demuxing example with the code provided and build the examples through `make`.

Ultimately, we'll have to provide this tool + build script in Symphonia's repository so people can run their own benchmarks. I'd probably use CMake for that.

**Comment by Shnatsel** [comment] 2023-01-29 22:19
`rustfft` doesn't appear to have any fuzz testing; I've opened an issue for that: https://github.com/ejmahler/RustFFT/issues/110

**Comment by richardpl** [comment] 2023-01-29 22:27
@Shnatsel maybe new release of ffmpeg, 6.0, will have null audio/video encoders so it will allow better benchmarks, but i need to test that they work as expected first.

**Comment by pdeljanov** [comment] 2023-01-30 02:11
Hey @Shnatsel, I managed to get it to build using the following command:

```
gcc -O3 ffbench.c -o ffbench $(pkg-config --cflags --libs libavformat libavcodec libavutil)
```

You'll need to apt-get `pkg-config` first if it's not already installed.

> `rustfft` doesn't appear to have any fuzz testing; I've opened an issue for that: [ejmahler/RustFFT#110](https://github.com/ejmahler/RustFFT/issues/110)

This probably isn't an issue for us because we only use FFTs of known fixed sizes, and the inputs are just floating point numbers.

**Comment by Shnatsel** [comment] 2023-01-30 03:51
Nope, still fails with the exact same errors. Even with

`sudo apt install libavformat-dev libavcodec-dev libavutil-dev pkg-config`

Maybe my ffmpeg 4.2.7 is just too old for this. I'll see if I can run this on a cloud VM instead, that way the results would be easy for anyone to reproduce.

**Comment by Shnatsel** [comment] 2023-01-30 15:39
Here are the results from an AMD EPYC Milan server processor, run on a Google Cloud `t2d-standard-4` VM instance.  (which is probably overkill and `t2d-standard-2` would have sufficed, or maybe even `t2d-standard-1`).

The performance differences appear to be quite stark on this processor, as if all other bottlenecks are removed and it's measuring the CPU performance directly.

[symphonia-amd-results.tar.gz](https://github.com/pdeljanov/Symphonia/files/10537253/symphonia-amd-results.tar.gz)

**Comment by richardpl** [comment] 2023-01-30 19:49
Still misleading, as 4.4.2 ffmpeg version does not have latest faster FFT/RDFT implementation.

**Comment by Shnatsel** [comment] 2023-01-30 19:54
Which released version has those optimizations?

**Comment by richardpl** [comment] 2023-01-30 21:55
5.1 partially (only in some filters and codecs), but fully included in 6.0 (to be released soon)

**Comment by pdeljanov** [comment] 2023-01-31 03:28
Hey @Shnatsel, so I looked at both of the Epyc benchmark sets. They follow very closely (similar relative percentage numbers) to what I see on my 4790k.

I think this indicates that the reason why your AMD system performed so much better isn't because it's a newer arch like we assumed, rather, you were just using an old version of ffmpeg. So I don't think it's worth the hassle to include it in the benchmarks anymore.

I have quite a number of further optimizations on-top of the ones I pushed earlier that I'm cleaning up now. The AAC, MP3, and Vorbis numbers look very close to what is currently published for the 4790k. Once I have that cleaned up I'll re-run all the benchmarks on the 4790k, RPi 4B, and M1 Pro using ffmpeg 5.1.2.

I think there's a good optimization opportunity in the IMDCT implementation, but without stable packed SIMD support I don't see how we can do it without allowing unsafe code again. Since the numbers are within the +/-15% as per the project goal, it's probably not worth it. Maybe `rustdct` will implement a SIMD accelerated IMDCT in the future that we can leverage.

**Comment by richardpl** [comment] 2023-01-31 08:16
Where are those ADPCM and rest of samples that are not mentioned in bench.py to compare?

**Comment by Shnatsel** [comment] 2023-01-31 14:07
Many projects make an exception for SIMD since it's impossible to achieve otherwise, and put it behind an optional feature. E.g. `png`, `jpeg`, and `zune-image` crates follow this pattern.

You could also publish the SIMD IMDCT it as a separate crate and make it an optional dependency. This will allow code reuse in other projects, too.

**Comment by richardpl** [comment] 2023-01-31 15:42
I must admit that benchmark results are still in direct contradiction with my testing. There just PCM is more than ~1.5 faster than yours. Albeit with 1.61 Rust compiler. And comparison by ignoring 6.0 version or master version of ffmpeg is very misleading.

**Comment by pdeljanov** [comment] 2023-02-01 01:18
I pushed the complete set of optimizations to the `experimental-opts` branch for testing. Please us an up-to-date compiler.

> Where are those ADPCM and rest of samples that are not mentioned in bench.py to compare?

The bench test utility is very out-of-date. I need someone to pick it up. I performed the current benchmarks with a random set of files from my personal music collection.

For PCM & ADPCM specifically I transcoded a few FLAC files using `ffmpeg`. You should be able to do the same. My files are 2 channel in the 4-5 minute range.

> I must admit that benchmark results are still in direct contradiction with my testing. There just PCM is more than ~1.5 faster than yours. Albeit with 1.61 Rust compiler. 

I did more experimentation and I don't think there's a contradiction here.

The performance difference only shows up with longer files. The files I tested are in the 4-5 minute (one song) range. I converted a 2 hour movie audio track to PCM, and I now see the performance difference. The difference also changes based on sample format. Again, only noticeable with longer files. There must be a higher fixed cost initializing `libavcodec`/`libavformat` that becomes apparent when decode times are short.

I also ran the same test but with `adpcm_ima_wav`, `adpcm_ms`, and `mp2` codecs. For those I see Symphonia being 1.26x, 0.94x, and 1.70x faster, respectively. I don't have a `mp1` encoder to test with.

Two things to note: I looked at the PCM decoder in `libavcodec`, and I see that it returns interleaved audio data. Symphonia always outputs in planar so there's an extra deinterleaving step. Symphonia also supports decoding PCM that's not 8, 16, 24, or 32-bit, which adds an additional shift per sample.

I now think that comparing the two would not be a fair comparison since one is a `memcpy` and the other is not. Would you agree we should remove the PCM benchmark?

> And comparison by ignoring 6.0 version or master version of ffmpeg is very misleading.

I disagree. It's perfectly reasonable to compare against the current latest release which is 5.1.2. When 6.0 is released I can re-run the benchmarks using that. As the document said: users who care about performance should perform their own benchmarks on their own systems.

To be clear, I intend to update the benchmarks with results for FFmpeg 5.1.2, Symphonia 0.5.2 (current stable), and a Symphonia 0.5.3 preview branch with the optimizations.

If your concerns have been addressed, I'll re-run the benchmarks on all the systems and update the page.

**Comment by pdeljanov** [comment] 2023-02-04 03:33
It occurred to me that you were likely building the demuxing/decoding example in-tree vs. us building it out-of-tree. If built out-of-tree, the `libav*` libraries are dynamically linked which adds overhead. So I added a new example and built it in-tree.

I've updated the benchmarks with the new methodology and the results are now published. The benchmark compares `master` vs. `master`.

@Shnatsel, it should be possible for you to run the benchmarks now since you need to compile `FFmpeg` from source and don't need to deal with OS packaging issues anymore. Heads up though, I switched to using significantly longer ADPCM and MP2 files since those codecs are so simple the relative difference doesn't show up without longer tracks.

**Comment by Shnatsel** [comment] 2023-02-07 04:03
`rustfft` provides NEON acceleration behind a feature flag that Symphonia doesn't set. It's only available starting with Rust 1.61, which is why it's feature-gated. Enabling this feature might help bridge the performance gap on ARM.

If it does indeed provide a benefit in benchmarks, it's a good idea to enable it - or expose as an optional feature if MSRV of 1.61 is too high.

**Comment by Shnatsel** [comment] 2023-02-07 04:04
Actually nevermind, the NEON acceleration is enabled by default. I misunderstood the documentation.

**Comment by pdeljanov** [comment] 2023-02-10 03:36
Since all the comments and requests have been addressed with the updated benchmarks, I will close this issue. Thanks for the insight on how to better benchmark against FFmpeg!

**Closed by pdeljanov** 2023-02-10 03:36 UTC
