### ISSUE TITLE
symphonia-play crashes on Windows 10 if the audio file's sample rate doesn't match the output device's default sample rate 

### ISSUE THREAD

**Issue by Herohtar** [pdeljanov/Symphonia#43] opened 2021-07-11 20:46 UTC
If I try to play an audio file that has a sample rate that is different than the sample rate that is set as the default format for my audio device, `symphonia-play` crashes. I'm guessing that this might not strictly be a bug, per se, but just a side effect of opening the default audio device with its default configuration. If so, I think to resolve this it would have to check the sample rate of the file before opening the device, then try to open the device using a matching sample rate. Is that correct?

```text
 ERROR symphonia_play::output::cpal > audio output stream open error: The requested stream configuration is not supported by the device.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OpenStreamError', symphonia-play\src\main.rs:248:74
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\release\symphonia-play.exe D:\test.flac` (exit code: 101)
```

**Comment by pdeljanov** [comment] 2021-07-11 21:02
Hmm, I don't think that's the issue because the audio device is opened [here](https://github.com/pdeljanov/Symphonia/blob/35accfec80d996abf05aeaa9e6a4f17e26b83535/symphonia-play/src/output.rs#L205-L209) which is only called by `symphonia-play` after the first audio buffer is decoded. So it should have the correct sample rate. This code is also used on macOS and it seems to work properly. :thinking: 

I think @BlackHoleFox had a similar issue. It may be device specific. Unfortunately I don't have a Windows machine easily accessible at the moment to debug this.

Perhaps try to check the sample rate (`spec.rate`) it's trying to open the device with?

**Comment by Herohtar** [comment] 2021-07-11 21:25
Ah, I was looking at the wrong thing. I checked, and `spec.rate` is the same rate that is listed in the printed track info, which is the sample rate that the file was exported as, so it's trying to open the device using the correct sample rate, but `build_output_stream` still returns that error.

It is definitely the sample rate that is causing the issue, because if I re-export the track with the same sample rate that I have set as my audio device's default output format, it will play. Alternatively, I can set my audio device's default output format to match the sample rate of the original track, and it will also play.

I suppose it could be that something about the audio device is not allowing it to be opened using a sample rate that isn't the default, though I'm not sure why. If it is something code-related, I guess it would be on `cpal`'s end though.

**Comment by pdeljanov** [comment] 2021-07-11 21:27
This is kinda confusing to me because shouldn't Windows be resampling the audio? My only guess then is that your audio device is operating in an exclusive mode?

**Comment by Herohtar** [comment] 2021-07-11 21:35
I would assume so, but I don't really know. Exclusive mode was enabled, but disabling it makes no difference, so it doesn't seem to be that. I also tested using a USB audio device, and it behaves the same way as my onboard sound card.

**Comment by BlackHoleFox** [comment] 2021-07-11 21:41
It seems to me like theres an issue with both the sample rate and channel count, depending on your device. The device that doesn't work for me has 6 channels by default. It only works if I configure Windows to say its only stereo and drop the default sample rate down to a track’s. Meanwhile my DAC, which is only stereo, works as long as I have its default sample rate set.

Ive found I can half-fix the channel issue by hardcoding `6` instead of the track’s count, but it sounds extremely wrong. The sound is all very shrill and sped up.

This second issue makes me more likely suspect something is opening a device wrong since I’ve never had another app fail opening a stereo track on the device with 6 channels.

**Comment by pdeljanov** [comment] 2021-07-11 21:49
Yeah, that's not gonna work lol. The issue is you'd be stuffing 3x stereo audio frames into into 1x 6 channel (guessing 5.1 system?) audio frame. So the audio will be sped up by 3x, and the channel map will be super wrong.

I don't really think it should be the app's responsibility to upmix the Stereo channels into 6 channels though so this continues to be weird.

**Comment by pdeljanov** [comment] 2021-07-11 21:56
If you modify the `SignalSpec` used to instantiate the `SampleBuffer` [here](https://github.com/pdeljanov/Symphonia/blob/b865e9d85ea95f5e665466a9636aa06b9985f3fa/symphonia-play/src/output.rs#L244) to match the channel count of the output device, then it should work properly. I hope. Can't say I've tested it. :stuck_out_tongue:

**Comment by Herohtar** [comment] 2021-07-11 21:59
My default audio device has 6 channels (it's set up to use 5.1 surround sound), but the USB audio device is just a stereo out, so only has the 2 channels. Since the USB device also exhibits the sample rate issue, I don't think the number of channels is related.

**Comment by BlackHoleFox** [comment] 2021-07-11 22:05
Weird. Like I said, faking my device to stereo in the sound control panel with the matching refresh rate makes it work, but only if both are applied.

**Comment by pdeljanov** [comment] 2021-07-11 22:10
This may be a limitation of Cpal using WASAPI (https://github.com/RustAudio/cpal/issues/263) though I haven't dug into it deeply enough to know for sure.

**Comment by BlackHoleFox** [comment] 2021-07-11 22:19
> If you modify the `SignalSpec` used to instantiate the `SampleBuffer` [here](https://github.com/pdeljanov/Symphonia/blob/b865e9d85ea95f5e665466a9636aa06b9985f3fa/symphonia-play/src/output.rs#L244) to match the channel count of the output device, then it should work properly. I hope. Can't say I've tested it. 😛
> 
> By doing that you'll end up feeding the OS silence for all the extra channels. Unfortunately I have no solution of the sample rate mismatch. Symphonia doesn't have a resampler since the OS should handle it.

I created a new spec with `SignalSpec::new_with_layout` with the previous spec’s sample rate and `Layout::FivePointOne` but with the channel hardcoding in the stream config, everything still had the 3x effect going on sadly.

**Comment by pdeljanov** [comment] 2021-07-11 22:32
Oh okay, I see where there could be an issue.

Well, it's not really an issue per-say. `SampleBuffer` and `RawSampleBuffer` are supposed to be "equivalent" to the `AudioBuffer` you're copying from (i.e., same channel count, duration, sample rate). Based on that assumption, some tweaks would need to be made to support this use-case to the `copy` routines.

Unfortunately, I can't make those changes today. Also, I'm not sure if I should since it raises some other questions such as channel mapping when up and down-mixing. Basically, it would work for the simple cases, but more complex cases would break in odd ways.

I viewed resampling and channel up/down-mix to be "signal processing" issues for another framework to solve and out of scope for a decoder framework. I could see arguments on either side though. Any thoughts?

**Comment by Herohtar** [comment] 2021-07-12 05:28
Since this appears to be on the `cpal` side, I've opened [an issue](https://github.com/RustAudio/cpal/issues/593) there, so maybe they'll be able to give some insight.

As a side note, the default format setting is for when the device is running in shared mode. Not sure if that is relevant to anything, but thought I would mention it since @pdeljanov asked about the device running in exclusive mode.

**Comment by BlackHoleFox** [comment] 2021-07-21 03:21
@pdeljanov given where the Rust ecosystem is for audio right now, I think there is something to be said for having one framework that can do most of the tasks you need. Then at that point, you toss it off to something like `cpal` or another OS library to say "play this with these settings." That simplicity would appeal to someone like me who doesn't know a tremendous amount about audio handling.

**Comment by pdeljanov** [comment] 2021-10-24 02:27
I gave `symphonia-play` a try in a virtual machine and confirmed the issue. Turns out this is fully expected behaviour. WASAPI doesn't perform resampling in shared mode so the application must match the device's sample rate. I'll look into using `dasp` for `symphonia-play`.

**Closed** 2023-01-14 03:40 UTC
