### ISSUE TITLE
Decoded frame count doesn't match the file's frame count

### ISSUE THREAD

**Issue by irh** [pdeljanov/Symphonia#85] opened 2021-12-10 16:13 UTC
First of all, thanks for making and sharing this library, I'm very happy to have discovered it, kudos!

I've noticed some behaviour that I don't understand while decoding some .wav files (I haven't checked all of their formats, but typically they're stereo 16bit, 44.1k, PCM).

Is it expected that the sum of all decoded `AudioBufferRef` frame counts should match the `n_frames` value defined in the track's codec params? I'm finding that in the last decoded packet, there are sometimes extra frames in the buffer, which then contain data that isn't in the file (e.g. Each buffer's frame count is `1158` through the file, then the final buffer contains `541` frames, when there are only `118` frames remaining according to the count).

I can share an example if you like but I figured I'd better check first if I'm just misunderstanding something in the API.

**Comment by pdeljanov** [comment] 2021-12-11 04:34
For the majority of formats, `n_frames` *should* match a manual frame count. I say *should* because if there are corrupted packets, or if the container declares an invalid frame count, there will likely be a discrepancy.

There are also a couple regular exceptions. Raw MP3s (\*.mp3), and AAC in the ADTS container  (\*.aac) don't provide a frame count so the length is estimated based on bitrate and file size. Symphonia will print a warning when it's estimating the length.

That being said, PCM in WAVE should definitely be accurate.

I'm actually not seeing this issue on my end with the files I test with, so could you provide me a sample?

**Comment by irh** [comment] 2021-12-13 15:36
Thanks @pdeljanov, I'll get back to you with an example or two as soon as I can.

**Comment by irh** [comment] 2021-12-14 15:44
@pdeljanov The files I'm working with are copyrighted so aren't shareable, but I had a look at a hexdump of some of the problem files, noticed that they had BWF info at the end of the file, and that led me to [this BWF test file](http://data.bbcarp.org.uk/saqas/bwf/panned_noise_bwf.wav) from [this page](https://www.bbc.co.uk/rd/publications/saqas), which exhibits the same behaviour (defined frame count: 576000, manually counted: 580222).

**Comment by pdeljanov** [comment] 2021-12-15 05:06
Hi @irh,

Thanks for the test file. I've found the issue and have a tentative solution. Give me a day or two to do some regression testing and then I'll push a fix to repo.

**Comment by irh** [comment] 2021-12-15 07:46
Great, no rush from my side as I've got the workaround of counting frames and exiting the loop once the count is reached. Thanks for investigating!

**Comment by pdeljanov** [comment] 2021-12-16 04:42
This should be fixed now. Feel free to let me know if you run into any other issues. Cheers!

**Closed** 2021-12-16 04:41 UTC

**Comment by orottier** [comment] 2022-01-06 19:36
I think we have run into the same issue in https://github.com/orottier/web-audio-api-rs/issues/42
Any chance you can release a new version containing the fix? Thanks a lot!

**Comment by pdeljanov** [comment] 2022-01-07 03:27
Hi @orottier,

I think you're right, that indeed looks very much like the same issue. Could you give your file a quick play-through with `symphonia-play` (`cargo run -- /path/to/your/file.wav`) at the latest commit to verify it is fixed?

If it is fixed then I can publish a new version of `symphonia-format-wav`.

**Comment by orottier** [comment] 2022-01-07 07:21
I can confirm the last decoded chunk is now 1338 samples instead of 1402. The audible click is gone.
Great succes :D

**Comment by pdeljanov** [comment] 2022-01-08 19:16
Hi @orottier,

I published v0.4.1 of `symphonia-format-wav`. You should be set.

**Comment by orottier** [comment] 2022-01-08 19:59
Much appreciated!

**Comment by orottier** [comment] 2022-01-09 19:09
Hi @pdeljanov, sorry to bother again. I'm using the wav-decoder via the main symphonia crate, could that one get a version bump too?

**Comment by pdeljanov** [comment] 2022-01-09 19:16
I think you can run `cargo update -p symphonia-format-wav`? The `symphonia` crate specifies version `^0.4` of the `symphonia-format-wav` so it should pick-up `0.4.1`.

**Comment by orottier** [comment] 2022-01-09 19:37
Ah, of course, I can add symphonia-format-wav to my Cargo.toml.... Thanks!

**Comment by pdeljanov** [comment] 2022-01-09 19:47
I could be wrong, but you shouldn't need to change your Cargo.toml.

I believe the issue is that you added `symphonia` to your `Cargo.toml` at `0.4.0`. Therefore, `symphonia` and all its sub-crates are now locked to `0.4.0` into your `Cargo.lock` file. Running `cargo update` should go through all your dependencies and pull the latest supported versions of them.

I thought `cargo update -p symphonia-format-wav` would do the trick, but maybe it's `cargo update -p symphonia` instead. You could just try `cargo update` if you don't mind having all your other dependencies updated.

**Comment by orottier** [comment] 2022-01-10 14:38
You are right, no changes needed. Sorry for the confusion
